### ISSUE TITLE
How is this method implemented in the code?

### ISSUE THREAD

**Issue by FedericaGielen** [YihongSun/Bayesian-Amodal#7]
Are eight shape templates devised for each object class？How is shape modeling implemented in the code? Would increasing the number of shape template of each object class improve the segmentation accuracy?
![25](https://github.com/YihongSun/Bayesian-Amodal/assets/145773794/7e933ce1-0db3-46db-b2df-23bd91f151ed)
![68](https://github.com/YihongSun/Bayesian-Amodal/assets/145773794/9519ee80-ae2c-44a2-98e9-7b5fa42557b8)

**Comment by YihongSun** [comment]
> Are eight shape templates devised for each object class？

Yes. The templates are constructed for each object class. Please refer to the [supplementary materials](https://yihongsun.github.io/files/cvpr22-amodal-supp.pdf) for more visualizations.

> How is shape modeling implemented in the code? 

The implementation is in `Code/Learn_mix_model_view_CA_it.py`.
Please refer to [L267](https://github.com/YihongSun/Bayesian-Amodal/blob/4ce9cbd03c7a5c713eb93c051efffefaa0db2ee5/Code/Learn_mix_model_view_CA_it.py#L267)-[L306](https://github.com/YihongSun/Bayesian-Amodal/blob/4ce9cbd03c7a5c713eb93c051efffefaa0db2ee5/Code/Learn_mix_model_view_CA_it.py#L306) for the construction of the shape prior. In essence, we apply a rough foreground-background binary segmentation in the feature space ([L56](https://github.com/YihongSun/Bayesian-Amodal/blob/4ce9cbd03c7a5c713eb93c051efffefaa0db2ee5/Code/Learn_mix_model_view_CA_it.py#L56)) and compile the foreground and context probabilities across all examples within the cluster 

> Would increasing the number of shape template of each object class improve the segmentation accuracy?

Yes, it would be an efficiency-performance trade-off since adding more templates would improve disentanglement of varying poses, but also increase the search space at inference time
