### ISSUE TITLE
How the parameters are learnt from features in unannotated images

### ISSUE THREAD

**Issue by FedericaGielen** [YihongSun/Bayesian-Amodal#9]
![123](https://github.com/YihongSun/Bayesian-Amodal/assets/145773794/5ccbb2f6-1c56-4e18-b996-88b10a740f37)
I am confused about how the parameters are learnt from features in unannotated images in the occlusion modeling.

**Comment by YihongSun** [comment]
Since the goal is to perform the outlier process for occlusion handling, the features for occlusion modeling (loaded [here](https://github.com/YihongSun/Bayesian-Amodal/blob/4ce9cbd03c7a5c713eb93c051efffefaa0db2ee5/Code/Net.py#L49C51-L49C51)) intend to model the average statistics across the natural images. Therefore, it does not need to be learned, and can simply be computed as the mean feature of randomly sampled natural images.
